[tool.poetry]
name = "drizzle-python-playground"
version = "0.1.0"
description = ""
authors = ["Caio Quintas"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiopg = "^1.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
